# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically from http://hub.culturegraph.org/entityfacts/context/v1/entityfacts.jsonld
require 'json/ld'
class JSON::LD::Context
  add_preloaded("http://hub.culturegraph.org/entityfacts/context/v1/entityfacts.jsonld") do
    new(term_definitions: {
      "xsd" => TermDefinition.new("xsd", id: "http://www.w3.org/2001/XMLSchema#", simple: true),
      "label" => TermDefinition.new("label", id: "http://www.w3.org/2000/01/rdf-schema#label", simple: true),
      "describedBy" => TermDefinition.new("describedBy", id: "http://www.w3.org/2007/05/powder-s#describedby", simple: true),
      "valid" => TermDefinition.new("valid", id: "http://schema.org/validFrom", type_mapping: "http://www.w3.org/2001/XMLSchema#dateTime"),
      "license" => TermDefinition.new("license", id: "http://purl.org/dc/terms/license", type_mapping: "@id"),
      "person" => TermDefinition.new("person", id: "http://d-nb.info/standards/elementset/gnd#Person", simple: true),
      "preferredName" => TermDefinition.new("preferredName", id: "http://d-nb.info/standards/elementset/gnd#preferredName", simple: true),
      "academicDegree" => TermDefinition.new("academicDegree", id: "http://d-nb.info/standards/elementset/gnd#academicDegree", language_mapping: "de"),
      "titleOfNobility" => TermDefinition.new("titleOfNobility", id: "http://d-nb.info/standards/elementset/gnd#titleOfNobility", language_mapping: "de"),
      "surname" => TermDefinition.new("surname", id: "http://d-nb.info/standards/elementset/gnd#surname", simple: true),
      "prefix" => TermDefinition.new("prefix", id: "http://d-nb.info/standards/elementset/gnd#prefix", simple: true),
      "forename" => TermDefinition.new("forename", id: "http://d-nb.info/standards/elementset/gnd#forename", simple: true),
      "placeOfBirth" => TermDefinition.new("placeOfBirth", id: "http://d-nb.info/standards/elementset/gnd#placeOfBirth", language_mapping: "de"),
      "placeOfDeath" => TermDefinition.new("placeOfDeath", id: "http://d-nb.info/standards/elementset/gnd#placeOfDeath", language_mapping: "de"),
      "placeOfActivity" => TermDefinition.new("placeOfActivity", id: "http://d-nb.info/standards/elementset/gnd#placeOfActivity", language_mapping: "de"),
      "variantName" => TermDefinition.new("variantName", id: "http://d-nb.info/standards/elementset/gnd#variantName", simple: true),
      "dateOfBirth" => TermDefinition.new("dateOfBirth", id: "http://d-nb.info/standards/elementset/gnd#dateOfBirth", simple: true),
      "dateOfDeath" => TermDefinition.new("dateOfDeath", id: "http://d-nb.info/standards/elementset/gnd#dateOfDeath", simple: true),
      "dateOfBirthAndDeath" => TermDefinition.new("dateOfBirthAndDeath", id: "http://d-nb.info/standards/elementset/gnd#dateOfBirthAndDeath", simple: true),
      "periodOfActivity" => TermDefinition.new("periodOfActivity", id: "http://d-nb.info/standards/elementset/gnd#periodOfActivity", simple: true),
      "affiliation" => TermDefinition.new("affiliation", id: "http://d-nb.info/standards/elementset/gnd#affiliation", simple: true),
      "biographicalOrHistoricalInformation" => TermDefinition.new("biographicalOrHistoricalInformation", id: "http://d-nb.info/standards/elementset/gnd#biographicalOrHistoricalInformation", language_mapping: "de"),
      "professionOrOccupation" => TermDefinition.new("professionOrOccupation", id: "http://d-nb.info/standards/elementset/gnd#professionOrOccupation", language_mapping: "de"),
      "gender" => TermDefinition.new("gender", id: "http://d-nb.info/standards/elementset/gnd#gender", language_mapping: "de"),
      "relatedPerson" => TermDefinition.new("relatedPerson", id: "http://d-nb.info/standards/elementset/gnd#relatedPerson", type_mapping: "http://d-nb.info/standards/elementset/gnd#Person"),
      "relationship" => TermDefinition.new("relationship", id: "http://vocab.org/relationship", type_mapping: "http://www.w3.org/2001/XMLSchema#string", language_mapping: "de"),
      "familialRelationship" => TermDefinition.new("familialRelationship", id: "http://d-nb.info/standards/elementset/gnd#familialRelationship", simple: true),
      "depiction" => TermDefinition.new("depiction", id: "http://xmlns.com/foaf/0.1/depiction", simple: true),
      "image" => TermDefinition.new("image", id: "http://xmlns.com/foaf/0.1/img", simple: true),
      "thumbnail" => TermDefinition.new("thumbnail", id: "http://xmlns.com/foaf/0.1/thumbnail", simple: true),
      "url" => TermDefinition.new("url", id: "http://xmlns.com/foaf/0.1/page", simple: true),
      "organisation" => TermDefinition.new("organisation", id: "http://d-nb.info/standards/elementset/gnd#CorporateBody", simple: true),
      "dateOfEstablishment" => TermDefinition.new("dateOfEstablishment", id: "http://d-nb.info/standards/elementset/gnd#dateOfEstablishment", simple: true),
      "dateOfTermination" => TermDefinition.new("dateOfTermination", id: "http://d-nb.info/standards/elementset/gnd#dateOfTermination", simple: true),
      "dateOfEstablishmentAndTermination" => TermDefinition.new("dateOfEstablishmentAndTermination", id: "http://d-nb.info/standards/elementset/gnd#dateOfEstablishmentAndTermination", simple: true),
      "founder" => TermDefinition.new("founder", id: "http://d-nb.info/standards/elementset/gnd#founder", simple: true),
      "placeOfBusiness" => TermDefinition.new("placeOfBusiness", id: "http://d-nb.info/standards/elementset/gnd#placeOfBusiness", simple: true),
      "associatedPlace" => TermDefinition.new("associatedPlace", id: "http://d-nb.info/standards/elementset/gnd#associatedPlace", simple: true),
      "topic" => TermDefinition.new("topic", id: "http://d-nb.info/standards/elementset/gnd#topic", simple: true),
      "precedingOrganisation" => TermDefinition.new("precedingOrganisation", id: "http://d-nb.info/standards/elementset/gnd#precedingCorporateBody", simple: true),
      "succeedingOrganisation" => TermDefinition.new("succeedingOrganisation", id: "http://d-nb.info/standards/elementset/gnd#succeedingCorporateBody", simple: true),
      "hierarchicallySuperiorOrganisation" => TermDefinition.new("hierarchicallySuperiorOrganisation", id: "http://d-nb.info/standards/elementset/gnd#hierarchicalSuperiorOfTheCorporateBody", simple: true),
      "relatedOrganisation" => TermDefinition.new("relatedOrganisation", id: "http://d-nb.info/standards/elementset/gnd#relatedCorporateBody", simple: true),
      "homepage" => TermDefinition.new("homepage", id: "http://d-nb.info/standards/elementset/gnd#homepage", simple: true),
      "sameAs" => TermDefinition.new("sameAs", id: "http://schema.org/sameAs", simple: true),
      "publisher" => TermDefinition.new("publisher", id: "http://purl.org/dc/terms/publisher", simple: true),
      "collection" => TermDefinition.new("collection", id: "http://d-nb.info/standards/elementset/dnb#isDescribedIn", simple: true),
      "name" => TermDefinition.new("name", id: "http://xmlns.com/foaf/0.1/name", simple: true),
      "abbr" => TermDefinition.new("abbr", id: "http://dbpedia.org/ontology/abbreviation", simple: true),
      "icon" => TermDefinition.new("icon", id: "http://xmlns.com/foaf/0.1/logo", simple: true)
    })
  end
end
