# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically from http://www.w3.org/ns/hydra/core
require 'json/ld'
class JSON::LD::Context
  add_preloaded("http://www.w3.org/ns/hydra/core") do
    new(term_definitions: {
      "hydra" => TermDefinition.new("hydra", id: "http://www.w3.org/ns/hydra/core#", simple: true),
      "rdf" => TermDefinition.new("rdf", id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#", simple: true),
      "rdfs" => TermDefinition.new("rdfs", id: "http://www.w3.org/2000/01/rdf-schema#", simple: true),
      "xsd" => TermDefinition.new("xsd", id: "http://www.w3.org/2001/XMLSchema#", simple: true),
      "owl" => TermDefinition.new("owl", id: "http://www.w3.org/2002/07/owl#", simple: true),
      "vs" => TermDefinition.new("vs", id: "http://www.w3.org/2003/06/sw-vocab-status/ns#", simple: true),
      "dc" => TermDefinition.new("dc", id: "http://purl.org/dc/terms/", simple: true),
      "cc" => TermDefinition.new("cc", id: "http://creativecommons.org/ns#", simple: true),
      "apiDocumentation" => TermDefinition.new("apiDocumentation", id: "http://www.w3.org/ns/hydra/core#apiDocumentation", simple: true),
      "ApiDocumentation" => TermDefinition.new("ApiDocumentation", id: "http://www.w3.org/ns/hydra/core#ApiDocumentation", simple: true),
      "title" => TermDefinition.new("title", id: "http://www.w3.org/ns/hydra/core#title", simple: true),
      "description" => TermDefinition.new("description", id: "http://www.w3.org/ns/hydra/core#description", simple: true),
      "entrypoint" => TermDefinition.new("entrypoint", id: "http://www.w3.org/ns/hydra/core#entrypoint", type_mapping: "@id"),
      "supportedClass" => TermDefinition.new("supportedClass", id: "http://www.w3.org/ns/hydra/core#supportedClass", type_mapping: "@vocab"),
      "Class" => TermDefinition.new("Class", id: "http://www.w3.org/ns/hydra/core#Class", simple: true),
      "supportedProperty" => TermDefinition.new("supportedProperty", id: "http://www.w3.org/ns/hydra/core#supportedProperty", type_mapping: "@id"),
      "SupportedProperty" => TermDefinition.new("SupportedProperty", id: "http://www.w3.org/ns/hydra/core#SupportedProperty", simple: true),
      "property" => TermDefinition.new("property", id: "http://www.w3.org/ns/hydra/core#property", type_mapping: "@vocab"),
      "required" => TermDefinition.new("required", id: "http://www.w3.org/ns/hydra/core#required", simple: true),
      "readonly" => TermDefinition.new("readonly", id: "http://www.w3.org/ns/hydra/core#readonly", simple: true),
      "writeonly" => TermDefinition.new("writeonly", id: "http://www.w3.org/ns/hydra/core#writeonly", simple: true),
      "supportedOperation" => TermDefinition.new("supportedOperation", id: "http://www.w3.org/ns/hydra/core#supportedOperation", type_mapping: "@id"),
      "Operation" => TermDefinition.new("Operation", id: "http://www.w3.org/ns/hydra/core#Operation", simple: true),
      "CreateResourceOperation" => TermDefinition.new("CreateResourceOperation", id: "http://www.w3.org/ns/hydra/core#CreateResourceOperation", simple: true),
      "ReplaceResourceOperation" => TermDefinition.new("ReplaceResourceOperation", id: "http://www.w3.org/ns/hydra/core#ReplaceResourceOperation", simple: true),
      "DeleteResourceOperation" => TermDefinition.new("DeleteResourceOperation", id: "http://www.w3.org/ns/hydra/core#DeleteResourceOperation", simple: true),
      "method" => TermDefinition.new("method", id: "http://www.w3.org/ns/hydra/core#method", simple: true),
      "expects" => TermDefinition.new("expects", id: "http://www.w3.org/ns/hydra/core#expects", type_mapping: "@vocab"),
      "returns" => TermDefinition.new("returns", id: "http://www.w3.org/ns/hydra/core#returns", type_mapping: "@vocab"),
      "statusCodes" => TermDefinition.new("statusCodes", id: "http://www.w3.org/ns/hydra/core#statusCodes", type_mapping: "@id"),
      "StatusCodeDescription" => TermDefinition.new("StatusCodeDescription", id: "http://www.w3.org/ns/hydra/core#StatusCodeDescription", simple: true),
      "statusCode" => TermDefinition.new("statusCode", id: "http://www.w3.org/ns/hydra/core#statusCode", simple: true),
      "Error" => TermDefinition.new("Error", id: "http://www.w3.org/ns/hydra/core#Error", simple: true),
      "Resource" => TermDefinition.new("Resource", id: "http://www.w3.org/ns/hydra/core#Resource", simple: true),
      "operation" => TermDefinition.new("operation", id: "http://www.w3.org/ns/hydra/core#operation", simple: true),
      "Collection" => TermDefinition.new("Collection", id: "http://www.w3.org/ns/hydra/core#Collection", simple: true),
      "member" => TermDefinition.new("member", id: "http://www.w3.org/ns/hydra/core#member", type_mapping: "@id"),
      "search" => TermDefinition.new("search", id: "http://www.w3.org/ns/hydra/core#search", simple: true),
      "freetextQuery" => TermDefinition.new("freetextQuery", id: "http://www.w3.org/ns/hydra/core#freetextQuery", simple: true),
      "PagedCollection" => TermDefinition.new("PagedCollection", id: "http://www.w3.org/ns/hydra/core#PagedCollection", simple: true),
      "totalItems" => TermDefinition.new("totalItems", id: "http://www.w3.org/ns/hydra/core#totalItems", simple: true),
      "itemsPerPage" => TermDefinition.new("itemsPerPage", id: "http://www.w3.org/ns/hydra/core#itemsPerPage", simple: true),
      "firstPage" => TermDefinition.new("firstPage", id: "http://www.w3.org/ns/hydra/core#firstPage", type_mapping: "@id"),
      "lastPage" => TermDefinition.new("lastPage", id: "http://www.w3.org/ns/hydra/core#lastPage", type_mapping: "@id"),
      "nextPage" => TermDefinition.new("nextPage", id: "http://www.w3.org/ns/hydra/core#nextPage", type_mapping: "@id"),
      "previousPage" => TermDefinition.new("previousPage", id: "http://www.w3.org/ns/hydra/core#previousPage", type_mapping: "@id"),
      "Link" => TermDefinition.new("Link", id: "http://www.w3.org/ns/hydra/core#Link", simple: true),
      "TemplatedLink" => TermDefinition.new("TemplatedLink", id: "http://www.w3.org/ns/hydra/core#TemplatedLink", simple: true),
      "IriTemplate" => TermDefinition.new("IriTemplate", id: "http://www.w3.org/ns/hydra/core#IriTemplate", simple: true),
      "template" => TermDefinition.new("template", id: "http://www.w3.org/ns/hydra/core#template", simple: true),
      "mapping" => TermDefinition.new("mapping", id: "http://www.w3.org/ns/hydra/core#mapping", simple: true),
      "IriTemplateMapping" => TermDefinition.new("IriTemplateMapping", id: "http://www.w3.org/ns/hydra/core#IriTemplateMapping", simple: true),
      "variable" => TermDefinition.new("variable", id: "http://www.w3.org/ns/hydra/core#variable", simple: true),
      "defines" => TermDefinition.new("defines", id: "http://www.w3.org/2000/01/rdf-schema#isDefinedBy", reverse_property: true),
      "comment" => TermDefinition.new("comment", id: "http://www.w3.org/2000/01/rdf-schema#comment", simple: true),
      "label" => TermDefinition.new("label", id: "http://www.w3.org/2000/01/rdf-schema#label", simple: true),
      "preferredPrefix" => TermDefinition.new("preferredPrefix", id: "http://purl.org/vocab/vann/preferredNamespacePrefix", simple: true),
      "cc:license" => TermDefinition.new("cc:license", id: "http://creativecommons.org/ns#license", type_mapping: "@id"),
      "cc:attributionURL" => TermDefinition.new("cc:attributionURL", id: "http://creativecommons.org/ns#attributionURL", type_mapping: "@id"),
      "domain" => TermDefinition.new("domain", id: "http://www.w3.org/2000/01/rdf-schema#domain", type_mapping: "@vocab"),
      "range" => TermDefinition.new("range", id: "http://www.w3.org/2000/01/rdf-schema#range", type_mapping: "@vocab"),
      "subClassOf" => TermDefinition.new("subClassOf", id: "http://www.w3.org/2000/01/rdf-schema#subClassOf", type_mapping: "@vocab"),
      "subPropertyOf" => TermDefinition.new("subPropertyOf", id: "http://www.w3.org/2000/01/rdf-schema#subPropertyOf", type_mapping: "@vocab"),
      "seeAlso" => TermDefinition.new("seeAlso", id: "http://www.w3.org/2000/01/rdf-schema#seeAlso", type_mapping: "@id")
    })
  end
end
