require 'json/ld'

module JSON::LD::Preloaded
  autoload :VERSION, "json/ld/preloaded/version"
end

# Require individual context files here
load "json/ld/preloaded/activitystreams.rb"
load "json/ld/preloaded/aesKeyWrapping.rb"
load "json/ld/preloaded/agever.rb"
load "json/ld/preloaded/btStatus.rb"
load "json/ld/preloaded/concealedId.rb"
load "json/ld/preloaded/csvw.rb"
load "json/ld/preloaded/datacube.rb"
load "json/ld/preloaded/dataIntegrityv1.rb"
load "json/ld/preloaded/dataIntegrityv2.rb"
load "json/ld/preloaded/dcc.rb"
load "json/ld/preloaded/did.rb"
load "json/ld/preloaded/ed25519sig2018.rb"
load "json/ld/preloaded/ed25519sig2020.rb"
load "json/ld/preloaded/entityfacts.rb"
load "json/ld/preloaded/foaf.rb"
load "json/ld/preloaded/geojson.rb"
load "json/ld/preloaded/hydra.rb"
load "json/ld/preloaded/iiif.rb"
load "json/ld/preloaded/linkedart.rb"
load "json/ld/preloaded/lov.rb"
load "json/ld/preloaded/oa.rb"
load "json/ld/preloaded/prefix.rb"
load "json/ld/preloaded/presentation.rb"
load "json/ld/preloaded/rdfa.rb"
load "json/ld/preloaded/research.rb"
load "json/ld/preloaded/schema.rb"
load "json/ld/preloaded/sha256HmacKey.rb"
load "json/ld/preloaded/vaccination.rb"
load "json/ld/preloaded/vc.rb"
load "json/ld/preloaded/vc2.rb"
load "json/ld/preloaded/vcard.rb"
load "json/ld/preloaded/vcRevoc.rb"
load "json/ld/preloaded/ver1.rb"
load "json/ld/preloaded/webKMS.rb"
load "json/ld/preloaded/x25519KeyAgr.rb"
load "json/ld/preloaded/zcap.rb"
